### ISSUE TITLE
Uncaught TypeError: $(...).tooltip is not a function

### ISSUE THREAD

**Issue by NickolasHu** [alibaba/Thera#54]
### Description

[Description of the issue]

### Steps to Reproduce

1. Connect a Android device using QR code.
2. Connect a iOS simulator.
3. This error throws.

**Expected behavior:** [What you expect to happen]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0-dev-4618d9c x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.5
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: $(...).tooltip is not a function

```
At /Applications/Thera.app/Contents/Resources/attach-package/weex-run/lib/realDeviceActionView.js:40

TypeError: $(...).tooltip is not a function
    at RealDeviceActionView.updateTooltip (/Applications/Thera.app/Contents/Resources/attach-package/weex-run/lib/realDeviceActionView.js:40:38)
    at RealDeviceActionView.connect (/Applications/Thera.app/Contents/Resources/attach-package/weex-run/lib/realDeviceActionView.js:30:14)
    at /Users/nickolas/Proj/falcon/weex-run-new/lib/thera-device-panel.js:63:28
    at Array.some (native)
    at DevicePanel.updateDeviceList (/Users/nickolas/Proj/falcon/weex-run-new/lib/thera-device-panel.js:53:18)
    at /Users/nickolas/Proj/falcon/weex-run-new/lib/thera-device-panel.js:16:87
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:265:29)
    at CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/app.asar/src/command-registry.js:166:19)
    at Object._dispatchUtf8 (/Applications/Thera.app/Contents/Resources/attach-package/weex-run/lib/wsBridge.js:73:21)
    at Object.dispatch (/Applications/Thera.app/Contents/Resources/attach-package/weex-run/lib/wsBridge.js:53:12)
    at Object.dispatch (/Applications/Thera.app/Contents/Resources/attach-package/weex-run/lib/wsBridge.js:23:21)
    at PreviewClient.onRecvCallback (/Users/nickolas/Proj/falcon/weex-run-new/lib/previewClient.js:156:23)
    at emitOne (events.js:96:13)
    at WebSocketConnection.emit (events.js:188:7)
    at WebSocketConnection.processFrame (/Applications/Thera.app/Contents/Resources/attach-package/weex-run/node_modules/websocket/lib/WebSocketConnection.js:547:26)
    at /Applications/Thera.app/Contents/Resources/attach-package/weex-run/node_modules/websocket/lib/WebSocketConnection.js:321:40
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
     -0:53 server:log (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:52.5.0 thera-debugger:inspector:recv (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:52.5.0 layer:updated (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:52 thera-debugger:inspector:recv (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:52 layer:updated (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:51.9.0 thera-debugger:inspector:recv (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:51.9.0 layer:updated (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
 22x -0:51.8.0 console:log (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:51.8.0 thera-debugger:inspector:recv (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:51.8.0 layer:updated (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
 53x -0:51.8.0 console:log (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:51.7.0 thera-debugger:inspector:recv (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:51.7.0 layer:updated (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:24 thera-device-panel:show (select#thera-simulator-selector.form-control-tools)
  2x -0:06.2.0 server:log (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:06.2.0 dumpling-server:client-changed (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
atom-beautify 0.29.19 
atom-jsx-transform 0.2.0 
atom-notifier 0.5.4 
atom-ternjs 0.18.3 
autocomplete-weex 0.1.1 
autocomplete-weexvue 0.1.2 
coffee-autocompile 0.6.2 
file-icons 2.0.17 
hyperclick 0.0.40 
js-hyperclick 1.11.0 
language-vue 0.23.0 
last-cursor-position 0.9.2 
linter 1.0.8 
linter-weex 0.1.4 
minimap 4.28.2 
open-terminal-here 2.3.0 
react 0.16.2 
seti-ui 1.3.5 
symbols-tree-view 0.13.14 
weex-run 1.1.36 
```

**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

You can get this information from copy and pasting the output of `thera --version ` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by scucheri** [comment]
solved
