### ISSUE TITLE
[symbols-tree-view]Uncaught TypeError: editor.getPath is not a function 

### ISSUE THREAD

**Issue by NickolasHu** [alibaba/Thera#62]
[Enter steps to reproduce:]

1. open settings view
2. open symbols tree view

**Thera**:0.6.4-dev.1
**Atom**: 1.18.0-dev-e6acfe3 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.5
**Thrown From**: [symbols-tree-view](https://github.com/xndcn/symbols-tree-view) package 0.13.17

### Stack Trace

Uncaught TypeError: editor.getPath is not a function

```
At /Applications/Thera.app/Contents/Resources/app/node_modules/symbols-tree-view/lib/symbols-tree-view.js:232

TypeError: editor.getPath is not a function
    at SymbolsTreeView.module.exports.SymbolsTreeView.populate (/Applications/Thera.app/Contents/Resources/app/node_modules/symbols-tree-view/lib/symbols-tree-view.js:232:32)
    at SymbolsTreeView.module.exports.SymbolsTreeView.toggle (/Applications/Thera.app/Contents/Resources/app/node_modules/symbols-tree-view/lib/symbols-tree-view.js:431:14)
    at atom-workspace.atom.commands.add.symbols-tree-view:toggle (/Applications/Thera.app/Contents/Resources/app/node_modules/symbols-tree-view/lib/main.js:58:42)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:265:29)
    at CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/app.asar/src/command-registry.js:166:19)
    at ToolBarButtonView.executeCallback (/app.asar/node_modules/tool-bar/lib/tool-bar-button-view.js:147:31)
    at ToolBarButtonView._onClick (/app.asar/node_modules/tool-bar/lib/tool-bar-button-view.js:106:22)
```

### Commands

```
     -0:39.7.0 symbols-tree-view:activate (atom-workspace.workspace.scrollbars-visible-always)
     -0:39.2.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:38.3.0 tool-bar:flash-devicelist (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
  9x -0:37.9.0 server:log (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:36.7.0 weex-run:ws-connected (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
  9x -0:36.7.0 thera-project-service:file-changed (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:36.6.0 thera-builder:push (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:34.1.0 thera-debugger:debugger:connection (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:34.1.0 server:log (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:34.1.0 thera-live-server:transformed (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:34.1.0 server:log (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:34.1.0 console.targets (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:34.1.0 thera-project-service:file-changed (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:34.1.0 thera-builder:push (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:30.4.0 window:toggle-dev-tools (div.panels-item)
     -0:20.5.0 symbols-tree-view:toggle (div.panels-item)
```

### Non-Core Packages

```
builder-plugin-weex 1.0.0 
coffee-autocompile 0.6.2 
file-icons 2.0.17 
hyperclick 0.0.40 
js-hyperclick 1.11.0 
language-vue 0.23.0 
last-cursor-position 0.9.2 
minimap 4.28.2 
open-terminal-here 2.3.0 
react 0.16.2 
```

**Comment by dengxu** [comment]
The issuse has bean fixed since version 0.6.4-dev.8.
